# Generated by Django 4.2.2 on 2023-06-25 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('housing_type', models.CharField(max_length=100)),
                ('terms', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default='', max_length=250)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misPerris.ciudad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misPerris.region')),
            ],
        ),
    ]
