# Generated by Django 4.2.2 on 2023-06-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0003_animal_alter_ciudad_region_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=10, default=10, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
