# Generated by Django 4.2.2 on 2023-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0004_animal_peso_animal_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
    ]
