# Generated by Django 4.2.2 on 2023-07-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0005_alter_animal_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.CharField(max_length=10),
        ),
    ]
