# Generated by Django 4.2.2 on 2023-07-05 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0008_customuser_city_customuser_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='misPerris.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
