# Generated by Django 4.2.2 on 2023-07-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0009_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
