# Generated by Django 4.2.2 on 2023-07-05 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0011_alter_solicitud_animal_alter_solicitud_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='misPerris.animal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
